name: Deploy Production (Discloud & GitHub Pages)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "deployments"
  cancel-in-progress: false

jobs:
  deploy-discloud:
    name: Deploy to Discloud
    runs-on: ubuntu-latest
    if: ${{ secrets.DISCLOUD_TOKEN != '' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Discloud
        uses: discloud/deploy-action@v1
        with:
          token: ${{ secrets.DISCLOUD_TOKEN }}
          app_id: "talvanebarber"

  deploy-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
